version: '3.1'

services:
  scheduler:
    image: "dask-lightgbm:${DOCKER_TAG}"
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: "dask-lightgbm:${DOCKER_TAG}"
    hostname: dask-worker
    environment:
      - SCHEDULER=tcp://scheduler:8786
    command: ["dask-worker", "--nprocs", "2", "--nthreads", "2", "--memory-limit", "1e9", "scheduler:8786"]

  client:
    image: "dask-lightgbm:${DOCKER_TAG}"
    hostname: dask-client
    environment:
      - SCHEDULER=tcp://scheduler:8786
    command: ["pytest", "system_tests"]
